development:
  adapter: postgresql
  database: otzovik_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: otzovik_test
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: otzovik_staging
  pool: 15
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'].to_s %>
  password: <%= ENV['DATABASE_PASSWORD'].to_s %>

production:
  adapter: postgresql
  database: otzovik_prod
  pool: 15
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'].to_s %>
  password: <%= ENV['DATABASE_PASSWORD'].to_s %>
